//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovare.Shop.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innovare.Shop.Business.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper name with type of &apos;{0}&apos; should ends with &apos;Mapper&apos;..
        /// </summary>
        internal static string MapperName {
            get {
                return ResourceManager.GetString("MapperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of mapper options with type of &apos;{0}&apos; should ends with &apos;Options&apos;..
        /// </summary>
        internal static string MapperOptionsName {
            get {
                return ResourceManager.GetString("MapperOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper section is not defined in the app setting file..
        /// </summary>
        internal static string MapperSectionNotFound {
            get {
                return ResourceManager.GetString("MapperSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service lifetime value is not valid.
        /// </summary>
        internal static string MapperServiceLifeTime {
            get {
                return ResourceManager.GetString("MapperServiceLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper with type of &apos;{0}&apos; should be a sealed class..
        /// </summary>
        internal static string NotSealedMapper {
            get {
                return ResourceManager.GetString("NotSealedMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator with type of &apos;{0}&apos; should be a sealed class..
        /// </summary>
        internal static string NotSealedValidator {
            get {
                return ResourceManager.GetString("NotSealedValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation section is not defined in the app setting file..
        /// </summary>
        internal static string ValidationSectionNotFound {
            get {
                return ResourceManager.GetString("ValidationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator name with type of &apos;{0}&apos; should ends with &apos;Validator&apos;..
        /// </summary>
        internal static string ValidatorName {
            get {
                return ResourceManager.GetString("ValidatorName", resourceCulture);
            }
        }
    }
}
