//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovare.Shop.Data.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPG.Common.SqlServer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EntityTypeConfiguration name with type of &apos;{0}&apos; should ends with &apos;EntityTypeConfiguration&apos;..
        /// </summary>
        internal static string EntityTypeConfigurationName
        {
            get
            {
                return ResourceManager.GetString("EntityTypeConfigurationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository with type of &apos;{0}&apos; should be a sealed class..
        /// </summary>
        internal static string NotSealedRepository
        {
            get
            {
                return ResourceManager.GetString("NotSealedRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnitOfWorks with type of &apos;{0}&apos; should be a sealed class..
        /// </summary>
        internal static string NotSealedUnitOfWorks
        {
            get
            {
                return ResourceManager.GetString("NotSealedUnitOfWorks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository name with type of &apos;{0}&apos; should ends with &apos;Repository&apos;..
        /// </summary>
        internal static string RepositoryName
        {
            get
            {
                return ResourceManager.GetString("RepositoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnitOfWorks name with type of &apos;{0}&apos; should ends with &apos;UnitOfWorks&apos;..
        /// </summary>
        internal static string UnitOfWorksName
        {
            get
            {
                return ResourceManager.GetString("UnitOfWorksName", resourceCulture);
            }
        }
    }
}
